Set up a "Hello world" project with Front End
AlselwiAisha/hello-react-front-end pull request #1
Opened 2024-01-17 18:52 UTC by AlselwiAisha

### Project requirements

- Create a new Rails API app called 'hello-rails-back-end'.
- Initialize your project with Git.
- Make sure that your project has a Postgres database set up.
- Create a table for storing your messages and create 5 different greetings.
- Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).
- Create a new React app called 'hello-react-front-end'
- Initialize your project with Git.
- Create the App component with react-router.
- Create the Greeting component that will display a greeting. Set it up as a route in your App component.
- Create a store, an action and a reducer that will connect to you API endpont to get the random greeting.
- Display the random greeting in your Greeting component.
- In the README file for the Rails API, add a link to your React app.
- Also, in the README file for the React app, add a link to your Rails API.
- When submitting for a review - use a link to the pull request in your Rails API.
- In the repo for the frontend part - include a PR with changes.

[Here is Back End](https://github.com/AlselwiAisha/hello-rails-back-end/pull/1)

2024-01-17 21:16 UTC, topeogunleye requested changes
Hi @AlselwiAisha, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
1. **Linking Backend and Frontend:**
   - Confirm that the link to the backend is present in the README of the frontend. This bidirectional linking ensures clarity and accessibility between the frontend and backend components. ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-17 21:16 UTC, topeogunleye commented on src/App.js
>    );
Hi there,

I've noticed that you've made some changes to the `App.js` file to include Redux and React Router. These are great additions, but I have a few suggestions to improve the code:

1. **Provider Usage**: The `Provider` component from `react-redux` is usually should be added, and the store should be provided from the redux.

3. **BrowserRouter**: You need to add a `BrowserRouter` component, and you haven't imported it. Make sure to import it from `react-router-dom` at the top of your file, and use it or else you could have error with react routers.

Here's how I would suggest modifying your code:

```javascript
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Provider } from 'react-redux';
import './App.css';
import Greeting from './Components/Greeting';
import store from './redux/store';

function App() {
  return (
    <Provider store={store}>
      <BrowserRouter>
        <div className="App">
          <header className="App-header">
            <Routes>
              <Route path="/" exact component={Greeting} />
            </Routes>
          </header>
        </div>
      </BrowserRouter>
    </Provider>
  );
}

export default App;

2024-01-18 04:25 UTC, shahadat3669 requested changes
Hi @AlselwiAisha, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Worked on previous reviewer comments.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 04:25 UTC, shahadat3669 commented on README.md
> +Here is the link to the [Hello Rails Back-End](https://github.com/AlselwiAisha/hello-rails-back-end/pull/1)repository.
👍 Great job on the progress made! To further align with project requirements, consider the following improvements:

- [ ] [Optional] **Link to Backend Repository:** As per project specifications, it's expected to provide a link to the backend repository in your project's README. Currently, the link redirects to the pull request, which doesn't fulfill this requirement. Please update the link to point directly to your backend repository.
![image](https://github.com/AlselwiAisha/hello-react-front-end/assets/55840999/85c72b03-ac93-4480-b5a3-d88f4b3cdc9d)

- [ ] [Optional] Additionally, it is requested that you submit your pull request for the `rails api` in the dashboard when you are requesting a review. For your next project, I recommend that you follow the documentation carefully and ensure that you use the proper link to request a review.
![image](https://github.com/AlselwiAisha/hello-react-front-end/assets/55840999/e713f602-6baf-45b3-9cb8-02dfb775f51d)

By making this adjustment, your project documentation will adhere to the project requirements more closely. Keep up the good work! 🚀👏

2024-01-18 04:25 UTC, shahadat3669 commented on src/redux/store.js
> +import thunk from 'redux-thunk';
- [ ] Great job so far! I've noticed that your `store` configuration doesn't match the [`redux-thunk`](https://github.com/reduxjs/redux-thunk?tab=readme-ov-file#manual-setup) documentation. I recommend taking a closer look at the documentation and configuring your app accordingly. 
![image](https://github.com/AlselwiAisha/hello-react-front-end/assets/55840999/2da66f37-8a09-43c8-827b-b9c5f9afdcb3)
- [ ] Additionally, I suggest checking your project locally and addressing any new errors that may arise.

2024-01-18 07:11 UTC, skyv26 requested changes
## Hi @AlselwiAisha, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjBkZWI1YTgxNDg4Y2QzMWU2MjkyNjQ2MmY1MmIzMjM4ZmI1MGU1OCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/fDWHJAmgrCeIw/giphy.gif)

## Highlights
- Altered the `redux` configuration ✅ 

## Required Changes ♻️

- [ ] Great work, you did a really great job, before reading further, please keep in mind you need to carefully read my suggestion on both the repository's PR. Your last code reviewer suggested you to implement the redux as per the standards and requirements, but it seems like while making changes to your `front-end` application. You messed up with the configuration, after carefully reviewing your project. I noticed that your redux code is not completely and not wired-up properly, which results in not getting any random greeting neither on `UI` nor `console.log`. Kindly fix the issue and make sure that your application is working as expected and without any problem. Kudos for implementing the backend very well and fix the cors issue requested  by your previous code reviewer.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-18 11:36 UTC, julie-ify approved these changes
Hi @AlselwiAisha, 

## Highlights!
- Good code organization and working FE app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-19 08:18 UTC, merged